name: Data Refresh

on: push
  #schedule:  
  #  - cron:  '0 */1 * * *'
jobs:
  build:
    name: refresh the dashboard
    runs-on: ubuntu-18.04 
    container: 
     image: rkrispin/us_electricity:dev.0.0.0.9000
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'main'
      - name: Data refresh
        run: |
            echo "$API_KEY"
            bash ./test.sh "$API_KEY"
        env:     
          API_KEY: ${{ secrets.TEST }}
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TEST }}
          # run: bash ./data_raw/data_refresh.sh "main" "$api_key"
